import { ScrollText } from "lucide-react";

/* ── Terms & Conditions sections ── */
const sections = [
  {
    title: "1. Acceptance of Terms",
    body: [
      "By accessing or using Dr. Crop — including the website, mobile application, and any related services (collectively, the \"Service\") — you agree to be bound by these Terms & Conditions. If you do not agree with any part of these terms, you must not use the Service.",
      "These terms apply to all visitors, users, and others who access or use Dr. Crop, whether on a free or paid plan.",
    ],
  },
  {
    title: "2. Description of Service",
    body: [
      "Dr. Crop is an AI-powered crop disease diagnosis platform. You upload a photograph of an affected plant, and the Service returns a structured report covering the likely disease, observable symptoms, probable causes, treatment options, and prevention strategies.",
      "The diagnosis provided is generated by artificial intelligence and is intended as preliminary, informational guidance only. It is not a substitute for professional agricultural, agronomic, or scientific consultation.",
    ],
  },
  {
    title: "3. Credits & Payments",
    body: [
      "Registered users receive 5 free diagnosis credits each day, which reset on a daily basis and do not carry over. Additional credits or premium features may be purchased through the plans described on our Pricing page.",
      "Payments are processed securely through Stripe. All fees are stated at the point of purchase. Except where required by law, payments are non-refundable once the associated credits have been consumed.",
      "We reserve the right to change pricing, credit allowances, and plan features at any time. Material changes will be communicated in advance where reasonably possible.",
    ],
  },
  {
    title: "4. Accounts & Security",
    body: [
      "To access certain features you must create an account and provide accurate, complete information. You are responsible for safeguarding your login credentials and for all activity that occurs under your account.",
      "You must notify us immediately of any unauthorised use of your account. We are not liable for any loss or damage arising from your failure to protect your credentials.",
    ],
  },
  {
    title: "5. Acceptable Use",
    body: [
      "You agree to use Dr. Crop only for lawful purposes. You must not upload content that is unlawful, infringing, or malicious, attempt to reverse-engineer or disrupt the Service, or use automated systems to access the Service in a manner that places an unreasonable load on our infrastructure.",
      "We reserve the right to suspend or terminate accounts that violate these terms or misuse the Service.",
    ],
  },
  {
    title: "6. Diagnostic Limitations & Disclaimer",
    body: [
      "AI-powered crop diagnosis is a decision-support tool, not a guarantee. Accuracy can be affected by image quality, lighting, symptom overlap between diseases, multiple concurrent infections, and environmental stress that mimics disease symptoms.",
      "Always confirm critical decisions — especially those involving pesticide application, quarantine, or the destruction of crops — with a qualified agronomist, agricultural extension officer, or local plant protection authority. Dr. Crop and its creators accept no liability for crop loss, financial loss, or other damages arising from reliance on the Service's output.",
    ],
  },
  {
    title: "7. Intellectual Property",
    body: [
      "The Service, including its software, design, branding, and content, is owned by Dr. Crop and protected by applicable intellectual property laws. You retain ownership of the images you upload, but grant us a limited licence to process them for the purpose of generating your diagnosis and improving the Service.",
    ],
  },
  {
    title: "8. Limitation of Liability",
    body: [
      "To the maximum extent permitted by law, Dr. Crop shall not be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the Service. Our total aggregate liability shall not exceed the amount you paid us in the twelve months preceding the claim.",
    ],
  },
  {
    title: "9. Changes to These Terms",
    body: [
      "We may update these Terms & Conditions from time to time. When we do, we will revise the \"last updated\" date below. Your continued use of the Service after changes take effect constitutes acceptance of the revised terms.",
    ],
  },
  {
    title: "10. Contact",
    body: [
      "If you have any questions about these Terms & Conditions, please reach out through our Support page or contact us at support@drcrop.app.",
    ],
  },
];

export default function Terms() {
  return (
    <section className="bg-white px-8 py-16">
      <div className="mx-auto max-w-4xl">
        {/* ── Header ── */}
        <div className="max-w-3xl">
          <p className="text-xs font-bold uppercase tracking-[0.24em] text-[#6F6F6F]">
            Legal
          </p>
          <h1 className="font-display mt-4 text-6xl leading-none tracking-tight text-black sm:text-7xl">
            Terms &amp; Conditions
          </h1>
          <p className="mt-6 text-lg leading-8 text-[#6F6F6F]">
            Please read these terms carefully before using Dr. Crop. They govern
            your access to and use of our AI-powered crop disease diagnosis
            platform.
          </p>
          <p className="mt-4 text-sm font-medium uppercase tracking-wider text-black/30">
            Last updated: 5 July 2026
          </p>
        </div>

        {/* ── Sections ── */}
        <div className="mt-14 grid gap-4">
          {sections.map((section) => (
            <article
              className="hairline-card rounded-[2rem] p-8"
              key={section.title}
            >
              <h2 className="font-display text-2xl text-black sm:text-3xl">
                {section.title}
              </h2>
              {section.body.map((paragraph, index) => (
                <p
                  className="mt-3 text-sm leading-7 text-[#6F6F6F]"
                  key={index}
                >
                  {paragraph}
                </p>
              ))}
            </article>
          ))}
        </div>

        {/* ── Footer note ── */}
        <div className="mt-10 flex items-start gap-3 rounded-[2rem] bg-[#F7F7F4] p-8">
          <ScrollText aria-hidden="true" className="mt-0.5 h-6 w-6 shrink-0 text-black" />
          <p className="text-sm leading-7 text-[#6F6F6F]">
            By using Dr. Crop, you acknowledge that you have read, understood, and
            agree to be bound by these Terms &amp; Conditions in their entirety.
          </p>
        </div>
      </div>
    </section>
  );
}
